<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <RootNamespace>SchoolInventoryScanner</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <ApplicationId>gr.nyxsystems.schoolinventoryscanner</ApplicationId>
    <ApplicationTitle>School Inventory Scanner</ApplicationTitle>
    <ApplicationDisplayVersion>0.4.1</ApplicationDisplayVersion>
    <ApplicationVersion>41</ApplicationVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.GooglePlayServices.Code.Scanner" Version="116.1.0.15" />
  </ItemGroup>

</Project>
